// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Bk6dJCkmEiUpNohnIT7g7XhJ0ZACsQQ',
    appId: '1:837087280574:web:81f695dbd47eb17a06cdef',
    messagingSenderId: '837087280574',
    projectId: 'shop-app-john',
    authDomain: 'shop-app-john.firebaseapp.com',
    storageBucket: 'shop-app-john.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8EZdWzV_Psbfij27bR5ac9AXYKKTf2Kk',
    appId: '1:837087280574:android:617ac3ffcf8b0aad06cdef',
    messagingSenderId: '837087280574',
    projectId: 'shop-app-john',
    storageBucket: 'shop-app-john.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0dx-qNOzKCQCsV0Eftd2wU5H5oRimvs4',
    appId: '1:837087280574:ios:dd43f5eddd8efec806cdef',
    messagingSenderId: '837087280574',
    projectId: 'shop-app-john',
    storageBucket: 'shop-app-john.appspot.com',
    iosClientId: '837087280574-79lik5v9v985r06n9o7761mb4tvgh6of.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0dx-qNOzKCQCsV0Eftd2wU5H5oRimvs4',
    appId: '1:837087280574:ios:dd43f5eddd8efec806cdef',
    messagingSenderId: '837087280574',
    projectId: 'shop-app-john',
    storageBucket: 'shop-app-john.appspot.com',
    iosClientId: '837087280574-79lik5v9v985r06n9o7761mb4tvgh6of.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
